name: odio

on: [push]

jobs:
  pytest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    container: python:${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock .

      - name: Run pytest tests
        run: |
          python -m pytest -x -v -W error --ignore=test/test_readme.py

  checks:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest flake8-alphabetize .
      - name: Run checks
        run: |
          black --check .
          flake8 .
          python -m pytest -x -v -W error test/test_readme.py
